config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :atvs do
    resources :bookings, only: [:new,:create]
  end
  resources :bookings, only: [:update, :destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atv.rb
class Atv < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :city, presence: true
  validates :description, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :atv
  validates :from, presence: true
  validates :to, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :atvs
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo])

    # For additional in app/views/devise/registrations/edit.html.erb
  end
end

app/controllers/atvs_controller.rb
class AtvsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def index

    if params[:city].blank?
      @atvs = Atv.all
    else
      @atvs = Atv.where("city ILIKE ?", "%#{params[:city]}%")
    end
  end

  def show
    @atv = Atv.find(params[:id])

    @booking = Booking.new
    @booking.atv_id = @atv.id

    @marker = {
      lng: @atv.longitude,
      lat: @atv.latitude
    }
  end

  def new
    @atv = Atv.new
  end

  def create
    @atv = Atv.new(atv_params)
    @atv.user = current_user
    if @atv.save
      @atv.user = current_user
      redirect_to atv_path(@atv)
    else
      render :new
    end
  end

  private

  def atv_params
    params.require(:atv).permit(:make, :model, :year, :price, :city, :description, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    # @atv = Atv.find(params[:atv_id])

    # @booking = Booking.new
    # @booking.atv = @atv
  end

  def create
    @atv = Atv.find(params[:atv_id])
    @booking = Booking.new(booking_params)
    @booking.confirmed = false
    @booking.atv = @atv
    @booking.user = current_user
    if @booking.save

      redirect_to bookings_path
    else
      render "atvs/show"
    end
  end

  def update
    @booking = Booking.find(params[:id])

    @booking.confirmed = true
    @booking.save
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to atv_path(@booking.atv)
  end

  private

  def booking_params
    params.require(:booking).permit(:from, :to, :atv_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/atvs/index.html.erb
<div class="containter">
  <h1 class= "index-title"><strong>ATV Listing</strong></h1>

    <div class="flex-container">
      <% @atvs.each do |atv| %>
        <%= link_to atv_path(atv.id) do %>
          <div class="atv-card"
          style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
              url('<%= cl_image_path atv.photo, height: 300, width: 400, crop: :fill %>')">
            <h2><%= atv.make %></h2>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/atvs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
<h3>New ATV</h3>

<%= simple_form_for(@atv) do |f| %>
<%= f.input :make %>
<%= f.input :model %>
<%= f.input :year %>
<%= f.input :price %>
<%= f.input :city %>
<%= f.input :description, as:  :text  %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
<%= f.submit%>
<% end %>

<p><%= link_to "Back to ATVs", atvs_path %></p>

  </div>
  </div>
</div>

app/views/atvs/show.html.erb
  <div class="container">



  <%= link_to "Back to Atvs", atvs_path %>

    <div class="my-container">

    <!-- <div id="logo"><%= image_tag "atv.png" %></div> -->
      <h1 class="title">My ATV</h1>

        <div class="top-banner">

          <div class="atv-container-show">
            <div class="atv-img" style="background-image: url('<%= cl_image_path @atv.photo,height: 400, width: 700, crop: :fill%>')">
            </div>

            <div class="spec-container">
              <h2> <strong>Make:</strong> <%= @atv.make %><h2>
              <h2><strong>Model:</strong> <%= @atv.model %><h2>
              <h2><strong>Year:</strong> <%=@atv.year%><h2>
            </div>
          </div>

          <div
            id="map"
            style="width: 50%;
            height: 800px;"
            data-marker="<%= @marker.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>

        </div>

      <h2 class="title">About My ATV</h2>
        <div class="btm-banner">

          <div class="atv-description">
            <h4><%= @atv.description %></h4>
          </div>

          <div class="img-avatar">
            <%= cl_image_tag @atv.user.photo,height: 150, width: 150, crop: :thumb,
             class: "img-circle" %>
             <h6><strong><%= @atv.user.email %></strong></h6>
            <h6>$ <%= @atv.price %></h6>
             <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">BOOK
             </button>
          </div>
<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Booking</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= simple_form_for ([@atv, @booking]) do |f| %>
            <%= f.input :from , as: :date, html5: true %>
            <%= f.input :to, as: :date, html5: true%>
            <%= f.submit %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

      </div>


  </div>

</div>

app/views/bookings/index.html.erb
<div class="bck">
<h1 class="middle-middle">Booking Logs</h1> <p><%= link_to "Back to Atvs", atvs_path %>

<div class="flex-container">

  <div >
    <h2 class="middle-middle">My Sent Requests</h2>

    <ul class="test-border middle-middle grayy   ">
      <% current_user.bookings.each do |book|  %>
      <div class="nohat grayy">
        <li>   <%=  cl_image_tag book.atv.user.photo, height: 50, width: 50, crop: :thumb, class: "img-circle"%> <%= book.atv.user.email %>'s   <strong> <%= book.atv.year %> <%= book.atv.make %> <%= book.atv.model %><strong> </li>
        <br>
        <li>  <%= book.from %>     <i class="fas fa-arrow-right"></i>     <%= book.to %></li>
        <li>Price: <%= ((book.to - book.from)* book.atv.price).to_i%>$</li>
        <% if book.confirmed == true %>
        <span class="label label-success">Accepted</span>
        <p>  </p>
        <span class="label label-danger">Cancel</span>
        <span class="label label-primary">Update</span>

        <% else %>
        <span class="label label-default">Pending</span>
        <p>  </p>
        <span class="label label-danger">Cancel</span>

        <span class="label label-primary">Update</span>
        <% end %>
        </div>
        <br>

      <% end %>
    </ul>
  </div>

  <div >
   <h2 class="middle-middle">Requestors </h2>

    <ul class="middle-middle ">
      <% current_user.atvs.each do |atv| %>
         <% unless atv.bookings.count == 0   %>

          <ul class="test-border grayy">

            <p > <strong> For : <%= atv.year %> <%= atv.make %> <%= atv.model %></strong> </p>
            <%  atv.bookings.each do |book| %>
            <div class="nohat">
              <li> <%= cl_image_tag book.user.photo,height: 50, width: 50, crop: :thumb, class: "img-circle" %>  <%= book.user.email %> is requesting your atv </li>
              <br>
              <li> From: <%= book.from %> <i class="fas fa-arrow-right"></i> To: <%= book.to %> </li>
              <li> Price: <%= (book.atv.price * (book.to - book.from)).to_i %>$ </li>
                <% if book.confirmed == false %>
                  <%= link_to "Accept", booking_path(book), method: :patch, class: "btn btn-success " %>
                  <%= link_to "Decline", booking_path(book), method: :patch, class: "btn btn-danger " %>

                <% else %>
                  <span class="label label-primary">Accepted</span>

                <% end %>


            </div>
            <br>
            <% end %>
          </ul>
          <br>
          <br>
        <% end %>
      <% end %>
    </ul>
  </div>


</div>


<i class="fas fa-arrow-alt-right"></i>
<i class="fas fa-arrow-alt-right"></i>
<i class="fas fa-arrow-alt-right"></i>

<div><i class="fas fa-arrow-alt-right"></i></div>



<!-- beforei had the name before the ul
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= favicon_link_tag %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>ATVs</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="outer-div" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2))">
    <%= video_tag "atvjumps.mp4",class: "video-element", autoplay: true, loop: true,muted: true %>
    <div class="home-txt-container">
      <h1 id="home-txt">Rent ATVs</h1>
      <h3 id="home-txt2">anytime, anywhere</h3>
      <%= link_to "Book Now", bookings_path, class: "btn btn-lg btn-primary " %>
    </div>
</div>


<div class="container">
  <div id="txt-container">
      <h3>NATIONWIDE</h3>
      <h3>AMAZING CHOICES</h3>
      <h3>EXCITING</h3>
  </div>

  <div class="list-container">
    <div id="mobile">
      <i class="fas fa-mobile-alt"></i>
      <h4>Go Mobile</h4>
      <h6>Manage Your Booking Logs from your mobile phone</h6>
    </div>
    <div id="choice">
      <i class="fas fa-search-plus"></i>
      <h4>Wide Range of Choices</h4>
      <h6>Easily browse all ATVs by Make or Model</h6>
    </div>
    <div id="request">
      <i class="fas fa-book"></i>
      <h4>Bookings Made Easy</h4>
      <h6>Verify who is looking to book your ATV with one click</h6>
    </div>
  </div>

<!-- Slideshow container -->
<div class="atv-specs-container">
  <div class="slideshow-container">

    <!-- Full-width images with number and caption text -->
    <div class="mySlides _fade" style="background-image: url('<%= image_path "atvrider4.jpg" %>')">
      <div class="numbertext">1 / 3</div>

      <div class="slide-text"><strong>YAMAHA</strong></div>
    </div>

    <div class="mySlides _fade" style="background-image: url('<%= image_path "atvrider1.jpg" %>')">
      <div class="numbertext">2 / 3</div>

      <div class="slide-text"><strong>KAWASKI</strong></div>
    </div>

    <div class="mySlides _fade" style="background-image: url('<%= image_path "atvrider5.jpg" %>')">

      <div class="numbertext">3 / 3</div>
      <div class="slide-text"><strong>SUZUKI</strong></div>
    </div>

      <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
    <div style="text-align:center">
      <span class="dot" onclick="currentSlide(1)"></span>
      <span class="dot" onclick="currentSlide(2)"></span>
      <span class="dot" onclick="currentSlide(3)"></span>
    </div>

  </div>
    <div class="atv-specs">
        <h3><strong>All-Terrain Vehicles</strong></h3>
      <ul>
        <li><h6>MAX Speed Mode</h6></li>
        <li><h6>Durable Suspensions</h6></li>
        <li><h6>Low-Fuel Consumption</h6></li>
        <li><h6>Off-Road Capabilities</h6></li>
        <li><h6>Low-Maintenance</h6></li>
        <li><h6>Titanium Rims</h6></li>
        <li><h6>Brembo Brakes</h6></li>
        <li><h6>Super Fun</h6></li>
        <li><h6>Just dont hurt yourself</h6></li>
      </ul>
    </div>
</div>


<div class="atv-specs-container">
    <div class="atv-specs">
        <h3><strong>Blast-Off Mode</strong></h3>
      <ul>
        <li><h6>Touch the Sky</h6></li>
        <li><h6>Maximum Speed</h6></li>
        <li><h6>Rocket Fuel</h6></li>
        <li><h6>Speed Demon</h6></li>
        <li><h6>Excite Bike</h6></li>
        <li><h6>Titanium Rims</h6></li>
        <li><h6>Brembo Brakes</h6></li>
        <li><h6>Super Fun</h6></li>
        <li><h6>Halleluijah!</h6></li>
      </ul>
    </div>

    <div class="atv" style="height:540px; width:1000px; background-image: url('https://images-eds-ssl.xboxlive.com/image?url=8Oaj9Ryq1G1_p3lLnXlsaZgGzAie6Mnu24_PawYuDYIoH77pJ.X5Z.MqQPibUVTc55gG82LeIcOp2KwfwW3vhTtdu8jJ83NVBfq1Hd9uPaEBZ_AFryU_RjzI3XoE9ZEx.Rjnhy8fL2nnLTUTr9.7DNqVw86uDe6IUd7.w.3WDWPjI53o34hN0p6ud_GaZEK5EfnmjxlvkqT9vhCDm1CpZaxp51YPhe5iL_AgxAgdyms-&h=1080&w=1920&format=jpg')">
    </div>
</div>
    <br>
    <div class="list-container">
    <div id="mobile">
      <i class="fab fa-instagram"></i>
      <h4>INSTAGRAM</h4>
      <h6>POSTING YOUR FUN AND RIDE</h6>
    </div>
    <div id="choice">
      <i class="fab fa-twitter"></i>
      <h4>TWITTER</h4>
      <h6>TWEETING YOUR EXCITEMENT</h6>
    </div>
    <div id="request">
      <i class="fab fa-facebook"></i>
      <h4>FACEBOOK</h4>
      <h6>YOUR FRIENDS WILL ENVY YOU</h6>
    </div>

  </div>



<div id="txt-footer">
  <h6><strong><%= link_to "RENT YOUR ATV NOW", new_atv_path%></strong></h6>
</div>
  <!-- The dots/circles -->

  <script>
  var slideIndex = 1;
  showSlides(slideIndex);

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("dot");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
  }
  </script>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-all_terrrain">
  <!-- Logo -->
  <a href="/" class="navbar-atv-logo">
    <%= image_tag "ATV-Logo.png"%>
  </a>
  <div class="search-box">
    <form id="search-city" class="form-inline" action="/atvs">
      <input name="city" type="text" class="form-control" placeholder="Enter City Name">
      <input type="submit" class="btn btn-primary" value="Search">
      <%# link_to "Search", atvs_path, class: "btn btn-primary" %>
    </form>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

      <%= link_to "Rent Your ATV", new_atv_path %>

      <%= link_to "Booking Logs", bookings_path %>

      <% if !user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path %>

        <%= link_to "Login", new_user_session_path %>


      <% end %>
    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <!-- <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"> -->
        <button class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">MENU</button>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>